# Generated by Django 2.2.12 on 2020-06-02 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='nome')),
                ('grade1', models.DecimalField(decimal_places=1, max_digits=3, verbose_name='A1')),
                ('grade2', models.DecimalField(decimal_places=1, max_digits=3, verbose_name='A2')),
            ],
            options={
                'verbose_name': 'nota',
                'verbose_name_plural': 'notas',
                'ordering': ('name',),
            },
        ),
    ]
